#!/usr/bin/env python3
"""Bake 640px WebP thumbnails for the intro PhotoField (GitHub Pages friendly)."""

from __future__ import annotations

import hashlib
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    raise SystemExit("pip install pillow")

from _paths import ROOT

PUBLIC = ROOT / "public"
OUT = PUBLIC / "photo-field"
MAX_EDGE = 640
WEBP_QUALITY = 78


def thumb_name(source: Path) -> str:
    rel = source.relative_to(PUBLIC).as_posix()
    digest = hashlib.sha1(rel.encode()).hexdigest()[:10]
    stem = source.stem.replace(" ", "-")[:32]
    return f"{stem}-{digest}.webp"


def bake(src: Path, dst: Path) -> None:
    with Image.open(src) as img:
        img = img.convert("RGB")
        w, h = img.size
        scale = min(1.0, MAX_EDGE / max(w, h, 1))
        if scale < 1.0:
            img = img.resize(
                (max(1, round(w * scale)), max(1, round(h * scale))),
                Image.Resampling.LANCZOS,
            )
        dst.parent.mkdir(parents=True, exist_ok=True)
        img.save(dst, "WEBP", quality=WEBP_QUALITY, method=6)


def main() -> None:
    sources: list[Path] = []
    for pattern in ("cities/**/*.webp", "spots/**/*.jpg", "spots/**/*.jpeg"):
        sources.extend(PUBLIC.glob(pattern))
    sources = sorted({p.resolve() for p in sources if p.is_file()})

    manifest: dict[str, str] = {}
    total_in = 0
    total_out = 0

    for src in sources:
        rel = "/" + src.relative_to(PUBLIC).as_posix()
        out = OUT / thumb_name(src)
        bake(src, out)
        manifest[rel] = "/" + out.relative_to(PUBLIC).as_posix()
        total_in += src.stat().st_size
        total_out += out.stat().st_size

    ts_path = ROOT / "src" / "data" / "photo-field-thumbs.ts"
    lines = [
        "// Auto-generated by scripts/build-photo-field-thumbs.py — do not edit.",
        "export const PHOTO_FIELD_THUMBS: Record<string, string> = {",
    ]
    for key in sorted(manifest):
        lines.append(f'  "{key}": "{manifest[key]}",')
    lines.append("};")
    lines.append("")
    ts_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Baked {len(manifest)} thumbs ({total_in // 1024}KB -> {total_out // 1024}KB)")


if __name__ == "__main__":
    main()
