#!/usr/bin/env python3
"""Import field photos from 素材 into public/spots and generate spot-images.ts.

Rules:
- Filename keywords must match spot 1:1 (more specific patterns first).
- Never copy one Baise spot's photos into another.
- Prefer confirmed names over 「推测」 when both exist.
"""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    raise SystemExit("pip install pillow")

try:
    import pillow_heif

    pillow_heif.register_heif_opener()
    HAS_HEIF = True
except ImportError:
    HAS_HEIF = False

from _paths import ROOT, assets_dir

ASSETS = assets_dir()
OUT = ROOT / "public" / "spots"
TS_OUT = ROOT / "src" / "data" / "spot-images.ts"
USER_STATUE = ROOT / "public" / "assets" / "deng-statue.jpg"

MAX_PER_SPOT = 24
MAX_EDGE = 1600
JPEG_QUALITY = 82

# More-specific keywords first. Never use bare 「博物馆」.
PATTERNS: list[tuple[str, list[str]]] = [
    ("deng-xiaoping-former-residence", ["邓小平故里", "小平故里", "故里会谈"]),
    ("siyuan-square", ["思源广场"]),
    ("intangible-heritage-experience", ["非遗文化体验馆", "非遗体验馆"]),
    ("guangan-museum", ["广安市博物馆", "博物馆 ("]),
    ("baise-uprising-monument-park", ["百色起义纪念园"]),
    ("baise-uprising-memorial", ["百色起义纪念馆"]),
    ("baise-integrity-education-base", ["廉政教育基地", "廉政教育", "铜鼓楼"]),
    ("guangdong-guild-hall", ["粤东会馆"]),
    ("qingfeng-lou", ["清风楼"]),
    ("youjiang-ethnic-museum", ["右江民族博物馆"]),
    ("jiefang-street", ["解放街"]),
    ("guangxi-labor-first-middle-school", ["劳动第一中学", "劳动一中", "广西劳动第一中学"]),
    ("lingzhou-guild-hall", ["灵洲会馆", "灵州会馆"]),
]

# Combined folders: first half → A, second half → B (stable, no cross-spot reuse elsewhere)
SPLIT_RULES: dict[str, tuple[str, str]] = {
    "右江民族博物馆与解放街": ("youjiang-ethnic-museum", "jiefang-street"),
    "劳动第一中学旧址与老街": (
        "guangxi-labor-first-middle-school",
        "jiefang-street",
    ),
}


def classify(name: str) -> str | None:
    for combined, (a, b) in SPLIT_RULES.items():
        if combined in name:
            m = re.search(r"_(\d+)\.(jpg|jpeg|heic)$", name, re.I)
            if not m:
                m = re.search(r"\((\d+)\)\.(jpg|jpeg|heic)$", name, re.I)
            idx = int(m.group(1)) if m else 1
            return a if idx % 2 == 1 else b
    for spot_id, keys in PATTERNS:
        for k in keys:
            if k in name:
                return spot_id
    return None


def sort_key(path: Path) -> tuple[int, str]:
    """Prefer non-推测, then natural filename order."""
    speculated = 1 if "推测" in path.name else 0
    return (speculated, path.name)


def save_image(src: Path, dest: Path) -> bool:
    dest.parent.mkdir(parents=True, exist_ok=True)
    ext = src.suffix.lower()
    if ext == ".heic" and not HAS_HEIF:
        return False
    try:
        with Image.open(src) as im:
            im = im.convert("RGB")
            w, h = im.size
            if max(w, h) > MAX_EDGE:
                ratio = MAX_EDGE / max(w, h)
                im = im.resize((int(w * ratio), int(h * ratio)), Image.Resampling.LANCZOS)
            im.save(dest, "JPEG", quality=JPEG_QUALITY, optimize=True)
        return True
    except Exception as e:
        print(f"  skip {src.name}: {e}")
        return False


def ensure_deng_statue(manifest: dict[str, list[str]]) -> None:
    """Keep formal statue as 01.jpg for 小平故里."""
    if not USER_STATUE.is_file():
        return
    spot_id = "deng-xiaoping-former-residence"
    dest_dir = OUT / spot_id
    dest_dir.mkdir(parents=True, exist_ok=True)
    existing = sorted(dest_dir.glob("*.jpg"))
    # Shift existing down if needed, write statue as 01
    temp_paths: list[Path] = []
    for i, src in enumerate(existing, start=2):
        tmp = dest_dir / f"_tmp_{i:02d}.jpg"
        shutil.copy2(src, tmp)
        temp_paths.append(tmp)
        src.unlink()
    statue_dest = dest_dir / "01.jpg"
    try:
        with Image.open(USER_STATUE) as im:
            im = im.convert("RGB")
            w, h = im.size
            if max(w, h) > MAX_EDGE:
                ratio = MAX_EDGE / max(w, h)
                im = im.resize((int(w * ratio), int(h * ratio)), Image.Resampling.LANCZOS)
            im.save(statue_dest, "JPEG", quality=85, optimize=True)
    except Exception as exc:
        print(f"  statue failed: {exc}")
        return

    paths = [f"/spots/{spot_id}/01.jpg"]
    for i, tmp in enumerate(temp_paths, start=2):
        if i > MAX_PER_SPOT:
            tmp.unlink(missing_ok=True)
            continue
        final = dest_dir / f"{i:02d}.jpg"
        tmp.rename(final)
        paths.append(f"/spots/{spot_id}/{i:02d}.jpg")
    manifest[spot_id] = paths
    print(f"{spot_id}: statue pinned as 01.jpg ({len(paths)} total)")


def write_manifest(manifest: dict[str, list[str]]) -> None:
    lines = [
        "// Auto-generated by scripts/import-spot-images.py — do not edit by hand",
        "",
        "export const SPOT_IMAGE_MANIFEST: Record<string, string[]> = "
        + json.dumps(manifest, ensure_ascii=False, indent=2)
        + ";",
        "",
        "export function getSpotImages(spotId: string): string[] {",
        "  return SPOT_IMAGE_MANIFEST[spotId] ?? [];",
        "}",
        "",
    ]
    TS_OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {TS_OUT}")


def main() -> None:
    buckets: dict[str, list[Path]] = {p[0]: [] for p in PATTERNS}

    for folder in ["四川", "广西"]:
        base = ASSETS / folder
        if not base.is_dir():
            print(f"missing assets folder: {base}")
            continue
        for f in sorted(base.iterdir(), key=sort_key):
            if f.suffix.lower() not in (".jpg", ".jpeg", ".heic"):
                continue
            if "住宿" in f.name:
                continue
            spot = classify(f.name)
            if spot and len(buckets[spot]) < MAX_PER_SPOT:
                buckets[spot].append(f)

    # Preserve web-only folders we won't refill from 素材 (copy to temp first)
    preserve_ids = {"siyuan-square"}
    preserved_bytes: dict[str, list[bytes]] = {}
    for spot_id in preserve_ids:
        src_dir = OUT / spot_id
        if src_dir.is_dir():
            blobs: list[bytes] = []
            for f in sorted(src_dir.glob("*.jpg")):
                blobs.append(f.read_bytes())
            if blobs:
                preserved_bytes[spot_id] = blobs

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    manifest: dict[str, list[str]] = {}

    for spot_id, files in buckets.items():
        paths: list[str] = []
        for i, src in enumerate(files, start=1):
            dest = OUT / spot_id / f"{i:02d}.jpg"
            if save_image(src, dest):
                paths.append(f"/spots/{spot_id}/{i:02d}.jpg")
        if paths:
            manifest[spot_id] = paths
            print(f"{spot_id}: {len(paths)} images")
        else:
            print(f"{spot_id}: 0 images (need web fill)")

    for spot_id, blobs in preserved_bytes.items():
        dest_dir = OUT / spot_id
        dest_dir.mkdir(parents=True, exist_ok=True)
        paths = []
        for i, data in enumerate(blobs, start=1):
            dest = dest_dir / f"{i:02d}.jpg"
            dest.write_bytes(data)
            paths.append(f"/spots/{spot_id}/{i:02d}.jpg")
        manifest[spot_id] = paths
        print(f"{spot_id}: {len(paths)} images (preserved)")

    ensure_deng_statue(manifest)
    write_manifest(manifest)

    # Uniqueness self-check for Baise
    print("\n=== Baise uniqueness check ===")
    baise = [s for s, _ in PATTERNS if s.startswith("baise") or s in {
        "guangdong-guild-hall", "qingfeng-lou", "youjiang-ethnic-museum",
        "jiefang-street", "guangxi-labor-first-middle-school", "lingzhou-guild-hall",
    }]
    hashes: dict[str, list[str]] = {}
    for spot_id in baise:
        for f in sorted((OUT / spot_id).glob("*.jpg")) if (OUT / spot_id).exists() else []:
            h = f.stat().st_size
            hashes.setdefault(f"{h}", []).append(f"{spot_id}/{f.name}")
    shared = {k: v for k, v in hashes.items() if len(v) > 1}
    if shared:
        print("WARNING: identical file sizes across spots (possible duplicates):")
        for k, v in list(shared.items())[:10]:
            print(f"  size={k}: {v}")
    else:
        print("OK: no identical sizes shared across Baise spot files")


if __name__ == "__main__":
    main()
