// Auto-generated by scripts/import-spot-images.py — do not edit by hand

export const SPOT_IMAGE_MANIFEST: Record<string, string[]> = {
  "baise-integrity-education-base": [
    "/spots/baise-integrity-education-base/01.jpg",
    "/spots/baise-integrity-education-base/02.jpg",
    "/spots/baise-integrity-education-base/03.jpg"
  ],
  "baise-uprising-memorial": [
    "/spots/baise-uprising-memorial/01.jpg",
    "/spots/baise-uprising-memorial/02.jpg",
    "/spots/baise-uprising-memorial/03.jpg"
  ],
  "baise-uprising-monument-park": [
    "/spots/baise-uprising-monument-park/01.jpg",
    "/spots/baise-uprising-monument-park/02.jpg",
    "/spots/baise-uprising-monument-park/03.jpg"
  ],
  "deng-xiaoping-former-residence": [
    "/spots/deng-xiaoping-former-residence/01.jpg",
    "/spots/deng-xiaoping-former-residence/02.jpg",
    "/spots/deng-xiaoping-former-residence/03.jpg",
    "/spots/deng-xiaoping-former-residence/04.jpg",
    "/spots/deng-xiaoping-former-residence/05.jpg",
    "/spots/deng-xiaoping-former-residence/06.jpg",
    "/spots/deng-xiaoping-former-residence/07.jpg",
    "/spots/deng-xiaoping-former-residence/08.jpg",
    "/spots/deng-xiaoping-former-residence/09.jpg",
    "/spots/deng-xiaoping-former-residence/10.jpg",
    "/spots/deng-xiaoping-former-residence/11.jpg",
    "/spots/deng-xiaoping-former-residence/12.jpg",
    "/spots/deng-xiaoping-former-residence/13.jpg",
    "/spots/deng-xiaoping-former-residence/14.jpg",
    "/spots/deng-xiaoping-former-residence/15.jpg",
    "/spots/deng-xiaoping-former-residence/16.jpg",
    "/spots/deng-xiaoping-former-residence/17.jpg",
    "/spots/deng-xiaoping-former-residence/18.jpg",
    "/spots/deng-xiaoping-former-residence/19.jpg",
    "/spots/deng-xiaoping-former-residence/20.jpg",
    "/spots/deng-xiaoping-former-residence/21.jpg",
    "/spots/deng-xiaoping-former-residence/22.jpg",
    "/spots/deng-xiaoping-former-residence/23.jpg",
    "/spots/deng-xiaoping-former-residence/24.jpg"
  ],
  "guangan-museum": [
    "/spots/guangan-museum/01.jpg",
    "/spots/guangan-museum/02.jpg",
    "/spots/guangan-museum/03.jpg",
    "/spots/guangan-museum/04.jpg",
    "/spots/guangan-museum/05.jpg",
    "/spots/guangan-museum/06.jpg",
    "/spots/guangan-museum/07.jpg",
    "/spots/guangan-museum/08.jpg",
    "/spots/guangan-museum/09.jpg",
    "/spots/guangan-museum/10.jpg",
    "/spots/guangan-museum/11.jpg",
    "/spots/guangan-museum/12.jpg",
    "/spots/guangan-museum/13.jpg",
    "/spots/guangan-museum/14.jpg",
    "/spots/guangan-museum/15.jpg",
    "/spots/guangan-museum/16.jpg",
    "/spots/guangan-museum/17.jpg",
    "/spots/guangan-museum/18.jpg",
    "/spots/guangan-museum/19.jpg",
    "/spots/guangan-museum/20.jpg",
    "/spots/guangan-museum/21.jpg",
    "/spots/guangan-museum/22.jpg",
    "/spots/guangan-museum/23.jpg",
    "/spots/guangan-museum/24.jpg"
  ],
  "guangdong-guild-hall": [
    "/spots/guangdong-guild-hall/01.jpg"
  ],
  "guangxi-labor-first-middle-school": [
    "/spots/guangxi-labor-first-middle-school/01.jpg",
    "/spots/guangxi-labor-first-middle-school/02.jpg",
    "/spots/guangxi-labor-first-middle-school/03.jpg"
  ],
  "intangible-heritage-experience": [
    "/spots/intangible-heritage-experience/01.jpg",
    "/spots/intangible-heritage-experience/02.jpg",
    "/spots/intangible-heritage-experience/03.jpg",
    "/spots/intangible-heritage-experience/04.jpg",
    "/spots/intangible-heritage-experience/05.jpg",
    "/spots/intangible-heritage-experience/06.jpg",
    "/spots/intangible-heritage-experience/07.jpg",
    "/spots/intangible-heritage-experience/08.jpg",
    "/spots/intangible-heritage-experience/09.jpg",
    "/spots/intangible-heritage-experience/10.jpg",
    "/spots/intangible-heritage-experience/11.jpg",
    "/spots/intangible-heritage-experience/12.jpg",
    "/spots/intangible-heritage-experience/13.jpg",
    "/spots/intangible-heritage-experience/14.jpg",
    "/spots/intangible-heritage-experience/15.jpg",
    "/spots/intangible-heritage-experience/16.jpg",
    "/spots/intangible-heritage-experience/17.jpg",
    "/spots/intangible-heritage-experience/18.jpg",
    "/spots/intangible-heritage-experience/19.jpg",
    "/spots/intangible-heritage-experience/20.jpg",
    "/spots/intangible-heritage-experience/21.jpg",
    "/spots/intangible-heritage-experience/22.jpg",
    "/spots/intangible-heritage-experience/23.jpg",
    "/spots/intangible-heritage-experience/24.jpg"
  ],
  "jiefang-street": [
    "/spots/jiefang-street/01.jpg",
    "/spots/jiefang-street/02.jpg",
    "/spots/jiefang-street/03.jpg"
  ],
  "lingzhou-guild-hall": [
    "/spots/lingzhou-guild-hall/01.jpg",
    "/spots/lingzhou-guild-hall/02.jpg",
    "/spots/lingzhou-guild-hall/03.jpg"
  ],
  "qingfeng-lou": [
    "/spots/qingfeng-lou/01.jpg",
    "/spots/qingfeng-lou/02.jpg",
    "/spots/qingfeng-lou/03.jpg"
  ],
  "siyuan-square": [
    "/spots/siyuan-square/01.jpg",
    "/spots/siyuan-square/02.jpg",
    "/spots/siyuan-square/03.jpg",
    "/spots/siyuan-square/04.jpg",
    "/spots/siyuan-square/05.jpg",
    "/spots/siyuan-square/06.jpg"
  ],
  "youjiang-ethnic-museum": [
    "/spots/youjiang-ethnic-museum/01.jpg",
    "/spots/youjiang-ethnic-museum/02.jpg",
    "/spots/youjiang-ethnic-museum/03.jpg"
  ]
};

export function getSpotImages(spotId: string): string[] {
  return SPOT_IMAGE_MANIFEST[spotId] ?? [];
}
